[phases.setup]

nixPkgs = ["...", "nodejs_20", "ffmpeg"]

[phases.install]

cmd = "npm install -g pnpm && pnpm install --frozen-lockfile --filter=server..."

[phases.build]

cmd = "cd server && pnpm run build"

[start]

cmd = "cd server && node dist/index.js"
